sudo: false
language: java
jdk: oraclejdk8
jdk: oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
 - git clone https://github.com/adminfaces/admin-theme.git ~/builds/admin-theme
 - cd ~/builds/admin-theme && mvn install
 - git clone https://github.com/adminfaces/admin-template.git ~/builds/admin-template
 - cd ~/builds/admin-template && mvn install
script:
  - cd $TRAVIS_BUILD_DIR && mvn clean package -Ptests
  - mvn clean package -Ptests -Pglassfish-managed
