dist: trusty
addons:
  chrome: stable
language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.arquillian"


#before_install: Not needed anymore cause theme and template are deployed to central snapshots on each commit
#- git clone https://github.com/adminfaces/admin-theme.git ~/builds/admin-theme
#- cd ~/builds/admin-theme && mvn install
#- git clone https://github.com/adminfaces/admin-template.git ~/builds/admin-template
#- cd ~/builds/admin-template && mvn install


before_script:
  - rm -r $HOME/.m2/repository/com/github/adminfaces/
  - git config --global http.postBuffer 157286400

script:
- mvn -U clean package -Pwildfly8-managed -Dbrowser=chromeheadless
- mvn test -Pglassfish-managed -Dbrowser=chromeheadless
- mvn test -Ptomee7-remote -Dbrowser=chromeheadless
- mvn test -Ptomee1.7-remote -Dbrowser=chromeheadless

after_success:
- mvn clean package -Pdocs -DskipTests
- mvn dockerfile:build -Pdocker
- mvn dockerfile:push -Pdocker