name: AdminFaces Showcase continuous integration

on: [push, pull_request]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8.0.212
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Script
        run: |
          $CHROMEWEBDRIVER/chromedriver
      - name: Maven Package
        run: mvn clean package -DskipTests
      - name: Wildfly-8
        run: mvn test -Ptests -Pwildfly8-managed -Dbrowser=chromeheadless
      - name: Glassfish-5
        run: mvn test -Ptests -Pwildfly8-managed -Dbrowser=chromeheadless
      - name: Tomee-7
        run: mvn test -Ptests -Ptomee7-remote -Dbrowser=chromeheadless
      - name: Tomee-1.7
        run: mvn test -Ptests -Ptomee1.7-remote -Dbrowser=chromeheadless